<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="AirlineReservationServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/AirlineReservationServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/AirlineReservationServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://service.webservice.dk.dtu/">
    <import location="AirlineReservationService.wsdl" namespace="http://service.webservice.dk.dtu/"/>
    <plnk:partnerLinkType name="AirlineReservationServiceLinkType">
        <plnk:role name="AirlineReservationServiceRole" portType="ns:AirlineReservationService"/>
    </plnk:partnerLinkType>
</definitions>
