<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ConcatServiceServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/ConcatServiceServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/ConcatServiceServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://concat.ws/">
    <import location="http://localhost:8080/ConcatApp/ConcatServiceService?wsdl" namespace="http://concat.ws/"/>
    <plnk:partnerLinkType name="ConcatServiceLinkType">
        <plnk:role name="ConcatServiceRole" portType="ns:ConcatService"/>
    </plnk:partnerLinkType>
</definitions>

