<?xml version="1.0" encoding="UTF-8"?>
<definitions name="studenregistration" targetNamespace="http://studentregistration"
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://studentregistration">
    <types>
        <xsd:schema targetNamespace="http://studentregistration" xmlns:tns="http://studentregistration">
            <xsd:complexType name="studentType">
                <xsd:sequence>
                    <xsd:element name="name" type="xsd:string"></xsd:element>
                </xsd:sequence>
            </xsd:complexType>
        </xsd:schema>
    </types>
</definitions>
